//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheClient.FaultyService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FaultyService.IFaultyService")]
    public interface IFaultyService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFaultyService/Sum", ReplyAction="http://tempuri.org/IFaultyService/SumResponse")]
        int Sum(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFaultyService/Sum", ReplyAction="http://tempuri.org/IFaultyService/SumResponse")]
        System.Threading.Tasks.Task<int> SumAsync(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFaultyService/SumWithFault", ReplyAction="http://tempuri.org/IFaultyService/SumWithFaultResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TheContracts.UnhandledError), Action="http://tempuri.org/IFaultyService/SumWithFaultUnhandledErrorFault", Name="UnhandledError", Namespace="http://schemas.datacontract.org/2004/07/TheContracts")]
        int SumWithFault(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFaultyService/SumWithFault", ReplyAction="http://tempuri.org/IFaultyService/SumWithFaultResponse")]
        System.Threading.Tasks.Task<int> SumWithFaultAsync(int a, int b);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFaultyServiceChannel : TheClient.FaultyService.IFaultyService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FaultyServiceClient : System.ServiceModel.ClientBase<TheClient.FaultyService.IFaultyService>, TheClient.FaultyService.IFaultyService {
        
        public FaultyServiceClient() {
        }
        
        public FaultyServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FaultyServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FaultyServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FaultyServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Sum(int a, int b) {
            return base.Channel.Sum(a, b);
        }
        
        public System.Threading.Tasks.Task<int> SumAsync(int a, int b) {
            return base.Channel.SumAsync(a, b);
        }
        
        public int SumWithFault(int a, int b) {
            return base.Channel.SumWithFault(a, b);
        }
        
        public System.Threading.Tasks.Task<int> SumWithFaultAsync(int a, int b) {
            return base.Channel.SumWithFaultAsync(a, b);
        }
    }
}
